// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schoolang_WebAPI.Data;

namespace Schoolang_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("Schoolang_WebAPI.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Francês",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Italiano",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Português",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Inglês",
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Alemão",
                            TeacherId = 5
                        });
                });

            modelBuilder.Entity("Schoolang_WebAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cellphone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cellphone = "33225555",
                            Name = "Marta",
                            Surname = "Kent"
                        },
                        new
                        {
                            Id = 2,
                            Cellphone = "3354288",
                            Name = "Paula",
                            Surname = "Isabela"
                        },
                        new
                        {
                            Id = 3,
                            Cellphone = "55668899",
                            Name = "Laura",
                            Surname = "Antonia"
                        },
                        new
                        {
                            Id = 4,
                            Cellphone = "6565659",
                            Name = "Luiza",
                            Surname = "Maria"
                        },
                        new
                        {
                            Id = 5,
                            Cellphone = "565685415",
                            Name = "Lucas",
                            Surname = "Machado"
                        },
                        new
                        {
                            Id = 6,
                            Cellphone = "456454545",
                            Name = "Pedro",
                            Surname = "Alvares"
                        },
                        new
                        {
                            Id = 7,
                            Cellphone = "9874512",
                            Name = "Paulo",
                            Surname = "José"
                        });
                });

            modelBuilder.Entity("Schoolang_WebAPI.Models.StudentLanguage", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("StudentLanguages");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            LanguageId = 2
                        },
                        new
                        {
                            StudentId = 1,
                            LanguageId = 4
                        },
                        new
                        {
                            StudentId = 1,
                            LanguageId = 5
                        },
                        new
                        {
                            StudentId = 2,
                            LanguageId = 1
                        },
                        new
                        {
                            StudentId = 2,
                            LanguageId = 2
                        },
                        new
                        {
                            StudentId = 2,
                            LanguageId = 5
                        },
                        new
                        {
                            StudentId = 3,
                            LanguageId = 1
                        },
                        new
                        {
                            StudentId = 3,
                            LanguageId = 2
                        },
                        new
                        {
                            StudentId = 3,
                            LanguageId = 3
                        },
                        new
                        {
                            StudentId = 4,
                            LanguageId = 1
                        },
                        new
                        {
                            StudentId = 4,
                            LanguageId = 4
                        },
                        new
                        {
                            StudentId = 4,
                            LanguageId = 5
                        },
                        new
                        {
                            StudentId = 5,
                            LanguageId = 4
                        },
                        new
                        {
                            StudentId = 5,
                            LanguageId = 5
                        },
                        new
                        {
                            StudentId = 6,
                            LanguageId = 1
                        },
                        new
                        {
                            StudentId = 6,
                            LanguageId = 2
                        },
                        new
                        {
                            StudentId = 6,
                            LanguageId = 3
                        },
                        new
                        {
                            StudentId = 6,
                            LanguageId = 4
                        },
                        new
                        {
                            StudentId = 7,
                            LanguageId = 1
                        },
                        new
                        {
                            StudentId = 7,
                            LanguageId = 2
                        },
                        new
                        {
                            StudentId = 7,
                            LanguageId = 3
                        },
                        new
                        {
                            StudentId = 7,
                            LanguageId = 4
                        },
                        new
                        {
                            StudentId = 7,
                            LanguageId = 5
                        });
                });

            modelBuilder.Entity("Schoolang_WebAPI.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lauro"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Roberto"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ronaldo"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rodrigo"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Alexandre"
                        });
                });

            modelBuilder.Entity("Schoolang_WebAPI.Models.Language", b =>
                {
                    b.HasOne("Schoolang_WebAPI.Models.Teacher", "Teacher")
                        .WithMany("Language")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Schoolang_WebAPI.Models.StudentLanguage", b =>
                {
                    b.HasOne("Schoolang_WebAPI.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schoolang_WebAPI.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
